version: '2.1'
services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   restart: always
  #   ports:
  #     - 15672:15672
  #   logging:
  #     options:
  #       max-size: "10m"
  #       max-file: "10"

  config:
    build: config
    restart: always
    ports:
      - 8888:8888

  registry:
    build: registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761

  gateway:
    build: gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000

  hello-service:
    build: hello-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8080:8080

  py-service:
    build: py-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8082:8082
