version: '2.1'
services:
  config:
    image: microkapibara_config
    build: config
    restart: always
    ports:
      - 8888:8888

  registry:
    image: microkapibara_registry
    build: registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761

  gateway:
    image: microkapibara_gateway
    build: gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000

  hello-service:
    image: microkapibara_hello-service
    build: hello-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "8080-8085:8080"

  py-service:
    image: microkapibara_py-service
    build: py-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "8086-8090:8082"
