hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

eureka:
  client:
    serviceURL:
      defaultZone: http://registry:8761/eureka