# hystrix:
#   command:
#     default:
#       execution:
#         isolation:
#           thread:
#             timeoutInMilliseconds: 10000

eureka:
  client:
    serviceURL:
      defaultZone: http://registry:8761/eureka

# spring:
#   rabbitmq:
#     host: rabbitmq